// Central data-testids for the app
export const IDS = {
  brand: "app-brand",
  scanBtn: "scan-trigger-button",
  scanFolderInput: "folder-path-input",
  useAcoustidToggle: "use-acoustid-toggle",
  seedBtn: "seed-sample-button",
  statusFilter: "status-filter-select",
  refreshBtn: "refresh-tracks-button",
  identifyAllBtn: "auto-identify-bulk-button",
  organizeBtn: "organize-library-button",
  fixBtn: (id) => `table-row-fix-${id}`,
  coverBtn: (id) => `table-row-cover-${id}`,
  modelSelect: "model-selector-dropdown",
  generateCover: "cover-art-generate-button",
  embedCover: "embed-cover-toggle",
  applyToFile: "apply-to-file-toggle",
  saveEdits: "save-edits-button",
  identifyOne: "identify-single-button",
  closeModal: "close-modal-button",
  statTotal: "stat-total",
  statIdentified: "stat-identified",
  statUnknown: "stat-unknown",
  statLow: "stat-low-confidence",
  tableRow: (id) => `track-row-${id}`,
};

export const IDS_DUP = {
  tabLibrary: "tab-library",
  tabDuplicates: "tab-duplicates",
  backBtn: "duplicates-back-button",
  runBtn: "duplicates-run-button",
  thresholdInput: "duplicates-threshold-input",
  diskToggle: "duplicates-disk-delete-toggle",
  deleteBtn: "duplicates-delete-selected-button",
  seedDupBtn: "seed-duplicates-button",
  group: (gid) => `duplicate-group-${gid}`,
  dupRow: (id) => `duplicate-row-${id}`,
  dupCheckbox: (id) => `duplicate-check-${id}`,
};
