// Central data-testids for the app
export const IDS = {
  brand: "app-brand",
  scanBtn: "scan-trigger-button",
  scanFolderInput: "folder-path-input",
  useAcoustidToggle: "use-acoustid-toggle",
  seedBtn: "seed-sample-button",
  statusFilter: "status-filter-select",
  refreshBtn: "refresh-tracks-button",
  identifyAllBtn: "auto-identify-bulk-button",
  organizeBtn: "organize-library-button",
  fixBtn: (id) => `table-row-fix-${id}`,
  coverBtn: (id) => `table-row-cover-${id}`,
  modelSelect: "model-selector-dropdown",
  generateCover: "cover-art-generate-button",
  embedCover: "embed-cover-toggle",
  applyToFile: "apply-to-file-toggle",
  saveEdits: "save-edits-button",
  identifyOne: "identify-single-button",
  closeModal: "close-modal-button",
  statTotal: "stat-total",
  statIdentified: "stat-identified",
  statUnknown: "stat-unknown",
  statLow: "stat-low-confidence",
  tableRow: (id) => `track-row-${id}`,
};
